import React from 'react';
import dynamic from 'next/dynamic';
import { demoPagesMenu, pageLayoutTypesPagesMenu, dashboardPagesMenu, budgetDashboard } from '../menu';
const DefaultAside = dynamic(() => import('../pages/_layout/_asides/DefaultAside'));
const BudgetAside = dynamic(() => import('../pages/_layout/_asides/BudgetAside'));


const asides = [
	// Admin side menu
	// {path: dashboardPagesMenu.financeMaster.subMenu.AllowanceRecovery.path, element: <DefaultAside />, exact: true },
	// {path: dashboardPagesMenu.financeMaster.subMenu.PayBand.path, element: <DefaultAside />, exact: true },
	// {path: dashboardPagesMenu.financeMaster.subMenu.PayMatrix.path, element: <DefaultAside />, exact: true },
	// {path: dashboardPagesMenu.financeMaster.subMenu.PayLevel.path, element: <DefaultAside />, exact: true },
	// {path: dashboardPagesMenu.financeMaster.subMenu.PayScaleYear.path, element: <DefaultAside />, exact: true },
	


	{ path: demoPagesMenu.adminsPage.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.registration.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.ScrutinyList.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.ScrutinyForm.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.registrationsMail.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.meritstudent.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.addemployee.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.employee.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.OutsourcedEmployees.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.education.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.body.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.medical.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.mastercode.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.DAConfig.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.DDOConfig.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.HRAConfig.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.payscaleyear.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.payband.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.paylevel.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.paymatrixdata.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.designation.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.branch.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.news.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.scrutiny.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.events.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.contact.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.tenders.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.galleryMaster.path, element: <DefaultAside />, exact: true },
	// { path: demoPagesMenu.galleryImage.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.circular.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.press_release.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.infrastructure.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.studentgrievance.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.posts.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.academicattendance.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.AttendancePage.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.studentphysiology.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.sportscience.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.StudentList.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.profile.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.employeeprofile.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.holidays.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.majorbudgethead.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.BudgetDashboard.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.submajorbudgethead.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.minorbudgethead.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.subminorbudgethead.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.nutritionalAssessment.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.studentNutritional.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.ResultReport.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.HostelReport.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.TrainingAssessmentReport.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.tournament.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.categories.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.parameter.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.categoryparameter.path, element: <DefaultAside />, exact: true },
	// { path: demoPagesMenu.sportParameter.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.playerassessment.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.Category.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.Parameter.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.Department.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.addplayerassessment.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.PerformanceStatus.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.ageRange.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.weightCategory.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.playerassessmentview.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.monitoring.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.intervention.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.TestAttendence.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.trainigAssessmnetDuration.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.sportsSubcategories.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.sportsWeightRange.path, element: <DefaultAside />, exact: true },

	{
		path: demoPagesMenu.trainigAssessmnetDurationUnit.path,
		element: <DefaultAside />,
		exact: true,
	},
	{ path: demoPagesMenu.employeeAttendance.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.employeeMonthlyAttendance.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.viewstudentNutritional.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.viewstudentphysiology.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.addemployeeattendance.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.achievement.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.addachievement.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.addbodyinjury.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.LevelOne.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.LevelTwo.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.sportsTrials.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.Weightage.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.AddAchievement.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.finalResult.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.candidateAttendence.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.sportsScienceMaster.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.sportsScience.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.updateCandidate.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.viewstudentinjury.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.applyleave.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.updatepassword.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.viewstudentattendance.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.hostel.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.hostelrooms.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.lessonPlanadmin.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.trainingPdf.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.adminExamSchedule.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.examtype.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.allsubject.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.subjectparameter.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.allexpense.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.expenseheads.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.examType2.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.income.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.allincomeheads.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.withdrawadmission.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.issueslc.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.LastestNews.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.liveStreaming.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.workShift.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.PushNotification.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.resultcriterion.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.achievementapprovereject.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.books.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.categorybooks.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.assignedhostelRoom.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.issuebooks.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.bulkresultdownload.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.transfercertificate.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.Email.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.sendSms.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.promotestudent.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.MessAdmin.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.admitCard.path, element: <DefaultAside />, exact: true },
	{
		path: demoPagesMenu.curriculumstructureandassessmentcriteria.path,
		element: <DefaultAside />,
		exact: true,
	},
	{ path: demoPagesMenu.developmentGoal.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.addstudentresults.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.studentregistrationdetails.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.withdrawApplication.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.amsStatics.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.promoteStudent.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.timetable.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.MessAdmin.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.meal.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.addtimetable.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.exceptionslog.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.academicsession.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.onlineclass.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.allbookstransaction.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.issueslc.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.selectbook.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.retrunBook.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.allRetrunBook.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.lms.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.addSubject.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.addChapter.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.mapSubject.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.addTopic.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.topicDetails.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.lmsTopic.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.classteacher.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.classes.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.miscellaneousEmployee.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.addMiscellaneousEmployee.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.ageCriteria.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.smsTemplate.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.eTemplate.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.venue.path, element: <DefaultAside />, exact: true },

	{
		path: demoPagesMenu.attendacemiscellaneousemployee.path,
		element: <DefaultAside />,
		exact: true,
	},
	{
		path: demoPagesMenu.pdfwithqr.path,
		element: <DefaultAside />,
		exact: true,
	},
	{ path: demoPagesMenu.aparParameter.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.aparRemarks.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.aparAssessment.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.aparList.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.aparView.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.detailsHead.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.objectHead.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.expenditure.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.sportassessment.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.budgetAllocation.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.AssessmentReport.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.ViewAssessmentReport.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.billType.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.taxSection.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.VoucherType.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.SubVoucherType.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.allImposedTaxes.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.billsubVoucher.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.client.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.addClient.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.allSubVoucher.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.addVoucherBill.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.allVoucherBill.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.unassignBill.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.BillPrint.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.StudentAdmission.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.candidateDetails.path, element: <DefaultAside />, exact: true },
	{ path: demoPagesMenu.coachFederation.path, element: <DefaultAside />, exact: true},
	{ path: dashboardPagesMenu.Salary.subMenu.CreateSalary.path, element: <DefaultAside />, exact: true },


	// Budget Dashboard 
	{ path: budgetDashboard.dashboard.path, element: <BudgetAside />, exact: true},
	{ path: budgetDashboard.Masters.subMenu.Imposed.path, element: <BudgetAside />, exact: true},
	{ path: budgetDashboard.Masters.subMenu.SubVoucherType.path, element: <BudgetAside />, exact: true},
	{ path: budgetDashboard.Masters.subMenu.VoucherType.path, element: <BudgetAside />, exact: true},
	{ path: budgetDashboard.Masters.subMenu.billType.path, element: <BudgetAside />, exact: true},
	{ path: budgetDashboard.budgetHeads.subMenu.detailsHead.path, element: <BudgetAside />, exact: true},
	{ path: budgetDashboard.Masters.subMenu.expenditure.path, element: <BudgetAside />, exact: true},
	{ path: budgetDashboard.budgetHeads.subMenu.majorbudgethead.path, element: <BudgetAside />, exact: true},
	{ path: budgetDashboard.budgetHeads.subMenu.minorbudgethead.path, element: <BudgetAside />, exact: true},
	{ path: budgetDashboard.budgetHeads.subMenu.objectHead.path, element: <BudgetAside />, exact: true},
	{ path: budgetDashboard.budgetHeads.subMenu.submajorbudgethead.path, element: <BudgetAside />, exact: true},
	{ path: budgetDashboard.budgetHeads.subMenu.subminorbudgethead.path, element: <BudgetAside />, exact: true},
	{ path: budgetDashboard.Masters.subMenu.taxSection.path, element: <BudgetAside />, exact: true},	
	// { path: budgetDashboard.budgetClient.subMenu.Addclient.path, element: <BudgetAside />, exact: true},	
	{ path: budgetDashboard.budgetClient.subMenu.Viewclient.path, element: <BudgetAside />, exact: true},	
	{ path: budgetDashboard.allSubVoucher.subMenu.AddSubVoucher.path, element: <BudgetAside />, exact: true},
	{ path: budgetDashboard.allSubVoucher.subMenu.ViewAllSubVoucher.path, element: <BudgetAside />, exact: true},
	{ path: budgetDashboard.BudegContingentBill.subMenu.AddContigentBill.path, element: <BudgetAside />, exact: true},	
	{ path: budgetDashboard.BudegContingentBill.subMenu.ViewContigentBill.path, element: <BudgetAside />, exact: true},	
	{ path: budgetDashboard.financeManagement.path, element: <BudgetAside />, exact: true},	
	{ path: budgetDashboard.BudgetEmployee.subMenu.EmployeeAttendanceInBudget.path, element: <BudgetAside />, exact: true},	
	{ path: budgetDashboard.BudgetEmployee.subMenu.EmployeeListInBudget.path, element: <BudgetAside />, exact: true},

	{ path: budgetDashboard.budgetHeads.subMenu.detailedHierarchy.path, element: <BudgetAside />, exact: true},
		

	

	{ path: demoPagesMenu.BudgetEmpProfile.path, element: <BudgetAside />, exact: true },
	{ path: demoPagesMenu.BudgetAddVoucherBill.path, element: <BudgetAside />, exact: true },
	{ path: demoPagesMenu.billSubVoucher.path, element: <BudgetAside />, exact: true },
	{ path: demoPagesMenu.AddClient.path, element: <BudgetAside />, exact: true},

	
];

export default asides;
