import React from 'react';
import { demoPagesMenu, pageLayoutTypesPagesMenu } from '../menu';
import DefaultFooter from '../pages/_layout/_footers/DefaultFooter';

const footers = [
	{ path: demoPagesMenu.adminsPage.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.registration.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.registrationsMail.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.meritstudent.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.addemployee.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.employee.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.OutsourcedEmployees.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.medical.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.mastercode.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.DAConfig.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.DDOConfig.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.HRAConfig.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.payscaleyear.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.payband.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.paylevel.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.paymatrixdata.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.employeeMonthlyAttendance.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.BudgetDashboard.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.majorbudgethead.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.submajorbudgethead.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.minorbudgethead.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.subminorbudgethead.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.designation.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.branch.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.contact.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.news.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.events.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.tenders.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.galleryMaster.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.sportsWeightRange.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.scrutiny.path, element: <DefaultFooter />, exact: true },


	// { path: demoPagesMenu.galleryImage.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.circular.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.sportsSubcategories.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.press_release.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.infrastructure.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.studentgrievance.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.posts.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.examtype.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.allsubject.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.subjectparameter.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.categories.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.parameter.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.categoryparameter.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.allexpense.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.expenseheads.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.examType2.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.income.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.allincomeheads.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.withdrawadmission.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.issueslc.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.LastestNews.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.liveStreaming.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.workShift.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.sendSms.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.Department.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.Parameter.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.Category.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.Category.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.smsTemplate.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.venue.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.eTemplate.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.PerformanceStatus.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.ageRange.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.weightCategory.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.TestAttendence.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.ageCriteria.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.coachFederation.path, element: <DefaultFooter />, exact: true },
	{ path: demoPagesMenu.unassignBill.path, element: <DefaultFooter />, exact: true },

	
];

export default footers;
