import React from 'react';
import {
	componentPagesMenu,
	dashboardPagesMenu,
	demoPagesMenu,
	pageLayoutTypesPagesMenu,
	budgetDashboard,
} from '../menu';
import AdminPageHeader from '../pages/_layout/_headers/admin-header/AdminHeader';
import DashboardBookingHeader from '../pages/_layout/_headers/DashboardBookingHeader';
import StudentPageHeader from '../pages/_layout/_headers/StudentDashboardHeader';
import TeacherPageHeader from '../pages/_layout/_headers/employeeHeader';
import CoachHeader from '../pages/_layout/_headers/coachHeader';
import PhysioHeader from '../pages/_layout/_headers/physioHeader';
import BudgetHeader from '../pages/_layout/_headers/Budget-header';
import SummaryHeader from '../pages/_layout/_headers/SummaryHeader';
import ProductsHeader from '../pages/_layout/_headers/ProductsHeader';
import ProductListHeader from '../pages/_layout/_headers/ProductListHeader';
import PageLayoutHeader from '../pages/_layout/_headers/PageLayoutHeader';
import ComponentsHeader from '../pages/_layout/_headers/ComponentsHeader';
import FormHeader from '../pages/_layout/_headers/FormHeader';
import ChartsHeader from '../pages/_layout/_headers/ChartsHeader';
import ContentHeader from '../pages/_layout/_headers/ContentHeader';
import UtilitiesHeader from '../pages/_layout/_headers/UtilitiesHeader';
import IconHeader from '../pages/_layout/_headers/IconHeader';
import DefaultHeader from '../pages/_layout/_headers/DefaultHeader';
import RegistrationsHeader from '../pages/_layout/_headers/registrationsHeader';

const headers = [
	// {path: dashboardPagesMenu.financeMaster.subMenu.AllowanceRecovery.path, element: <AdminPageHeader />, exact: true },
	// 	{path: dashboardPagesMenu.financeMaster.subMenu.PayBand.path, element: <AdminPageHeader />, exact: true },
	// 	{path: dashboardPagesMenu.financeMaster.subMenu.PayMatrix.path, element: <AdminPageHeader />, exact: true },
	// 	{path: dashboardPagesMenu.financeMaster.subMenu.PayLevel.path, element: <AdminPageHeader />, exact: true },
	// 	{path: dashboardPagesMenu.financeMaster.subMenu.PayScaleYear.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.adminsPage.path, element: <AdminPageHeader />, exact: true },

	{ path: demoPagesMenu.promoteStudent.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.registration.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.ScrutinyList.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.ScrutinyForm.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.registrationsMail.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.meritstudent.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.addemployee.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.employee.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.OutsourcedEmployees.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.education.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.medical.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.mastercode.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.DAConfig.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.DDOConfig.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.payscaleyear.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.payband.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.paylevel.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.paymatrixdata.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.HRAConfig.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.designation.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.branch.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.branch.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.news.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.events.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.contact.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.tenders.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.TestAttendence.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.galleryMaster.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.galleryImage.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.circular.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.press_release.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.infrastructure.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.studentgrievance.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.profile.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.posts.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.body.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.employeeprofile.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.holidays.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.majorbudgethead.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.minorbudgethead.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.subminorbudgethead.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.sportsWeightRange.path, element: <AdminPageHeader />, exact: true },
	// { path: demoPagesMenu.attendance.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.academicattendance.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.sportsSubcategories.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.AttendancePage.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.StudentList.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.studentphysiology.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.sportscience.path, element: <AdminPageHeader />, exact: true },
	// { path: demoPagesMenu.sportsparameterCategroy.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.tournament.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.categories.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.parameter.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.categoryparameter.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.BudgetDashboard.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.lessonPlanadmin.path, element: <AdminPageHeader />, exact: true },
	// { path: demoPagesMenu.sportParameter.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.nutritionalAssessment.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.Category.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.Parameter.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.scrutiny.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.Department.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.studentNutritional.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.playerassessment.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.addplayerassessment.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.playerassessmentview.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.PerformanceStatus.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.ageRange.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.weightCategory.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.monitoring.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.intervention.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.updatepassword.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.trainingPdf.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.adminExamSchedule.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.examtype.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.allsubject.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.subjectparameter.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.allexpense.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.examType2.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.income.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.allincomeheads.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.withdrawadmission.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.LastestNews.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.liveStreaming.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.workShift.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.sendSms.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.resultcriterion.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.assignedhostelRoom.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.issuebooks.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.bulkresultdownload.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.PushNotification.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.Email.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.transfercertificate.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.sendSms.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.promotestudent.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.timetable.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.MessAdmin.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.meal.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.books.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.categorybooks.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.addtimetable.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.exceptionslog.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.academicsession.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.onlineclass.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.issueslc.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.allbookstransaction.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.selectbook.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.retrunBook.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.allRetrunBook.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.lms.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.expenseheads.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.addSubject.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.ageCriteria.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.addChapter.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.mapSubject.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.addTopic.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.lmsTopic.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.topicDetails.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.ResultReport.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.HostelReport.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.eTemplate.path, element: <AdminPageHeader />, exact: true },
	{
		path: demoPagesMenu.TrainingAssessmentReport.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{ path: demoPagesMenu.classteacher.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.classes.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.miscellaneousEmployee.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.finalResult.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.sportsTrials.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.Weightage.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.AddAchievement.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.candidateAttendence.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.sportsScienceMaster.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.sportsScience.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.updateCandidate.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.admitCard.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.pdfwithqr.path, element: <AdminPageHeader />, exact: true },
	{ path: demoPagesMenu.venue.path, element: <AdminPageHeader />, exact: true },

	{
		path: demoPagesMenu.addMiscellaneousEmployee.path,
		element: <AdminPageHeader />,
		exact: true,
	},

	{
		path: demoPagesMenu.achievementapprovereject.path,
		element: <AdminPageHeader />,
		exact: true,
	},

	{
		path: demoPagesMenu.studentregistrationdetails.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.withdrawApplication.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.addstudentresults.path,
		element: <AdminPageHeader />,
		exact: true,
	},

	{ path: demoPagesMenu.viewstudentattendance.path, element: <AdminPageHeader />, exact: true },
	{
		path: demoPagesMenu.curriculumstructureandassessmentcriteria.path,
		element: <AdminPageHeader />,
		exact: true,
	},

	{
		path: demoPagesMenu.trainigAssessmnetDuration.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.trainigAssessmnetDurationUnit.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.employeeAttendance.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.employeeMonthlyAttendance.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.viewstudentNutritional.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.viewstudentphysiology.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.addemployeeattendance.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.achievement.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.LevelOne.path,
		element: <AdminPageHeader />,
		exact: true,
	},

	{
		path: demoPagesMenu.LevelTwo.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.addachievement.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.addbodyinjury.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.viewstudentinjury.path,
		element: <AdminPageHeader />,
		exact: true,
	},

	{
		path: demoPagesMenu.applyleave.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.hostel.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.hostelrooms.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.amsStatics.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.developmentGoal.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.aparParameter.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.aparRemarks.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.aparAssessment.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.aparList.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.aparView.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.detailsHead.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.objectHead.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.expenditure.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.sportassessment.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.submajorbudgethead.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.budgetAllocation.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.AssessmentReport.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.ViewAssessmentReport.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.billType.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.taxSection.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.VoucherType.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.SubVoucherType.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.allImposedTaxes.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.billsubVoucher.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.client.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.addClient.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.allSubVoucher.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.addVoucherBill.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.allVoucherBill.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.unassignBill.path,
		element: <AdminPageHeader />,
		exact: true,
	},

	{
		path: demoPagesMenu.BillPrint.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.StudentAdmission.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.createSalary.path,
		element: <AdminPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.candidateDetails.path,
		element: <AdminPageHeader />,
		exact: true,
	},

	{ path: demoPagesMenu.examresult.path, element: <StudentPageHeader />, exact: true },
	{ path: demoPagesMenu.studentDashboard.path, element: <StudentPageHeader />, exact: true },
	{ path: demoPagesMenu.Attendance.path, element: <StudentPageHeader />, exact: true },

	{ path: demoPagesMenu.lmsStudent.path, element: <StudentPageHeader />, exact: true },
	{ path: demoPagesMenu.studentIntervention.path, element: <StudentPageHeader />, exact: true },
	{ path: demoPagesMenu.studentMonitoring.path, element: <StudentPageHeader />, exact: true },
	{ path: demoPagesMenu.assessmentReport.path, element: <StudentPageHeader />, exact: true },
	{ path: demoPagesMenu.studentExamSchedule.path, element: <StudentPageHeader />, exact: true },
	{ path: demoPagesMenu.studentupdatepassword.path, element: <StudentPageHeader />, exact: true },
	{ path: demoPagesMenu.studentLms.path, element: <StudentPageHeader />, exact: true },
	{ path: demoPagesMenu.lmsStudentTopic.path, element: <StudentPageHeader />, exact: true },
	{
		path: demoPagesMenu.studentNutritionalDetails.path,
		element: <StudentPageHeader />,
		exact: true,
	},
	{ path: demoPagesMenu.studentMedicalDetails.path, element: <StudentPageHeader />, exact: true },
	{ path: demoPagesMenu.AcademicTimetable.path, element: <StudentPageHeader />, exact: true },
	// { path: demoPagesMenu.TrainingSchedule.path, element: <StudentPageHeader />, exact: true },
	// { path: demoPagesMenu.dietChart.path, element: <StudentPageHeader />, exact: true },
	{ path: demoPagesMenu.Attendance.path, element: <StudentPageHeader />, exact: true },
	{ path: demoPagesMenu.Attendance.path, element: <StudentPageHeader />, exact: true },

	{ path: demoPagesMenu.assessment.path, element: <StudentPageHeader />, exact: true },
	// { path: demoPagesMenu.reportCard.path, element: <StudentPageHeader />, exact: true },
	// { path: demoPagesMenu.lessonplan.path, element: <StudentPageHeader />, exact: true },
	{ path: demoPagesMenu.coachProfile.path, element: <CoachHeader />, exact: true },
	{ path: demoPagesMenu.coachTrainingSch.path, element: <CoachHeader />, exact: true },
	{ path: demoPagesMenu.coachProfileAttendance.path, element: <CoachHeader />, exact: true },
	{ path: demoPagesMenu.coachapar.path, element: <CoachHeader />, exact: true },
	{ path: demoPagesMenu.coachFederation.path, element: <CoachHeader />, exact: true },
	{ path: demoPagesMenu.coachAddapar.path, element: <CoachHeader />, exact: true },
	{ path: demoPagesMenu.coachReportapar.path, element: <CoachHeader />, exact: true },
	{ path: demoPagesMenu.coachAllapar.path, element: <CoachHeader />, exact: true },
	{ path: demoPagesMenu.coachFinalApar.path, element: <CoachHeader />, exact: true },
	{ path: demoPagesMenu.coachReport.path, element: <CoachHeader />, exact: true },
	{ path: demoPagesMenu.aparPrintCoach.path, element: <CoachHeader />, exact: true },
	{ path: demoPagesMenu.coachReview.path, element: <CoachHeader />, exact: true },
	{ path: demoPagesMenu.coachLeave.path, element: <CoachHeader />, exact: true },
	{ path: demoPagesMenu.PlayerAssessment.path, element: <CoachHeader />, exact: true },
	{ path: demoPagesMenu.AddPlayerAssessment.path, element: <CoachHeader />, exact: true },
	{ path: demoPagesMenu.PlayerAssessmentView.path, element: <CoachHeader />, exact: true },
	{ path: demoPagesMenu.employeeProfile.path, element: <TeacherPageHeader />, exact: true },
	{ path: demoPagesMenu.teacherExamSchedule.path, element: <TeacherPageHeader />, exact: true },
	{ path: demoPagesMenu.employeeapplyLeave.path, element: <TeacherPageHeader />, exact: true },
	{ path: demoPagesMenu.addacademictimetable.path, element: <TeacherPageHeader />, exact: true },
	{ path: demoPagesMenu.onlineClass.path, element: <TeacherPageHeader />, exact: true },
	{ path: demoPagesMenu.lessonPlanteacher.path, element: <TeacherPageHeader />, exact: true },
	{ path: demoPagesMenu.addexaminationresult.path, element: <TeacherPageHeader />, exact: true },
	{ path: demoPagesMenu.physioInjury.path, element: <TeacherPageHeader />, exact: true },
	{ path: demoPagesMenu.examination.path, element: <TeacherPageHeader />, exact: true },
	{ path: demoPagesMenu.apar.path, element: <TeacherPageHeader />, exact: true },
	{ path: demoPagesMenu.aparReport.path, element: <TeacherPageHeader />, exact: true },
	{ path: demoPagesMenu.AparReview.path, element: <TeacherPageHeader />, exact: true },
	{ path: demoPagesMenu.allAparReports.path, element: <TeacherPageHeader />, exact: true },
	{ path: demoPagesMenu.viewALLaparList.path, element: <TeacherPageHeader />, exact: true },
	{ path: demoPagesMenu.viewApar.path, element: <TeacherPageHeader />, exact: true },
	{ path: demoPagesMenu.aparSelgAPAR.path, element: <TeacherPageHeader />, exact: true },
	{ path: demoPagesMenu.aparPrint.path, element: <TeacherPageHeader />, exact: true },
	{ path: demoPagesMenu.smsTemplate.path, element: <TeacherPageHeader />, exact: true },
	{ path: demoPagesMenu.teacherLms.path, element: <TeacherPageHeader />, exact: true },
	{
		path: demoPagesMenu.tacherbulkresultdownload.path,
		element: <TeacherPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.attendacemiscellaneousemployee.path,
		element: <AdminPageHeader />,
		exact: true,
	},

	{
		path: demoPagesMenu.employeeProfileAttendance.path,
		element: <TeacherPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.physioMonitoring.path,
		element: <PhysioHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.BillRequest.path,
		element: <TeacherPageHeader />,
		exact: true,
	},
	{
		path: demoPagesMenu.TeacherBill.path,
		element: <TeacherPageHeader />,
		exact: true,
	},

	{ path: demoPagesMenu.physioIntervention.path, element: <PhysioHeader />, exact: true },
	{ path: demoPagesMenu.physioProfile.path, element: <PhysioHeader />, exact: true },
	{ path: demoPagesMenu.physioDashboard.path, element: <PhysioHeader />, exact: true },
	{ path: demoPagesMenu.physioaddBodyInjury.path, element: <PhysioHeader />, exact: true },
	{ path: demoPagesMenu.BodyInjury.path, element: <PhysioHeader />, exact: true },
	{ path: demoPagesMenu.physilogyassessment.path, element: <PhysioHeader />, exact: true },
	{ path: demoPagesMenu.nutritionalassessment.path, element: <PhysioHeader />, exact: true },
	{ path: demoPagesMenu.Physiostudentphysiology.path, element: <PhysioHeader />, exact: true },
	{ path: demoPagesMenu.physiostudentNutritional.path, element: <PhysioHeader />, exact: true },
	{ path: demoPagesMenu.physiotherapistmedical.path, element: <PhysioHeader />, exact: true },
	{ path: demoPagesMenu.physiotherapistphysiology.path, element: <PhysioHeader />, exact: true },
	{ path: demoPagesMenu.nutritionalMess.path, element: <PhysioHeader />, exact: true },
	{ path: demoPagesMenu.nutritionalAddMenu.path, element: <PhysioHeader />, exact: true },
	{ path: demoPagesMenu.ApplyPhsioLeave.path, element: <PhysioHeader />, exact: true },
	{ path: demoPagesMenu.home.path, element: <RegistrationsHeader />, exact: true },
	// { path: demoPagesMenu.registrationform.path, element: <RegistrationsHeader />, exact: true },
	{ path: demoPagesMenu.levelone.path, element: <RegistrationsHeader />, exact: true },
	{ path: demoPagesMenu.leveltwo.path, element: <RegistrationsHeader />, exact: true },
	{ path: demoPagesMenu.assessmentTA.path, element: <RegistrationsHeader />, exact: true },
	{ path: demoPagesMenu.assessmentViewTA.path, element: <RegistrationsHeader />, exact: true },
	{ path: demoPagesMenu.assessmentAddTA.path, element: <RegistrationsHeader />, exact: true },
	{ path: demoPagesMenu.lreport.path, element: <RegistrationsHeader />, exact: true },
	{ path: demoPagesMenu.lTworeport.path, element: <RegistrationsHeader />, exact: true },


	//Budget Header 

	{ path: budgetDashboard.dashboard.path, element: <BudgetHeader />, exact: true },
	{ path: budgetDashboard.Masters.subMenu.Imposed.path, element: <BudgetHeader />, exact: true },
	{ path: budgetDashboard.Masters.subMenu.SubVoucherType.path, element: <BudgetHeader />, exact: true},
	{ path: budgetDashboard.Masters.subMenu.VoucherType.path, element: <BudgetHeader />, exact: true},
	{ path: budgetDashboard.Masters.subMenu.billType.path, element: <BudgetHeader />, exact: true},
	{ path: budgetDashboard.budgetHeads.subMenu.detailsHead.path, element: <BudgetHeader />, exact: true},
	{ path: budgetDashboard.Masters.subMenu.expenditure.path, element: <BudgetHeader />, exact: true},
	{ path: budgetDashboard.budgetHeads.subMenu.majorbudgethead.path, element: <BudgetHeader />, exact: true},
	{ path: budgetDashboard.budgetHeads.subMenu.minorbudgethead.path, element: <BudgetHeader />, exact: true},
	{ path: budgetDashboard.budgetHeads.subMenu.objectHead.path, element: <BudgetHeader />, exact: true},
	{ path: budgetDashboard.budgetHeads.subMenu.submajorbudgethead.path, element: <BudgetHeader />, exact: true},
	{ path: budgetDashboard.budgetHeads.subMenu.subminorbudgethead.path, element: <BudgetHeader />, exact: true},	
	{ path: budgetDashboard.Masters.subMenu.taxSection.path, element: <BudgetHeader />, exact: true},
    { path: budgetDashboard.allSubVoucher.subMenu.AddSubVoucher.path, element: <BudgetHeader />, exact: true},
	{ path: budgetDashboard.allSubVoucher.subMenu.ViewAllSubVoucher.path, element: <BudgetHeader />, exact: true},
	{ path: budgetDashboard.BudegContingentBill.subMenu.AddContigentBill.path, element: <BudgetHeader />, exact: true},	
	{ path: budgetDashboard.BudegContingentBill.subMenu.ViewContigentBill.path, element: <BudgetHeader />, exact: true},	

	{ path: budgetDashboard.financeManagement.path, element: <BudgetHeader />, exact: true},
	// { path: budgetDashboard.budgetClient.subMenu.Addclient.path, element: <BudgetHeader />, exact: true},	
    { path: budgetDashboard.budgetClient.subMenu.Viewclient.path, element: <BudgetHeader />, exact: true},		
	{ path: demoPagesMenu.BudgetAddVoucherBill.path, element: <BudgetHeader />, exact: true },
	{ path: demoPagesMenu.AddClient.path, element: <BudgetHeader />, exact: true },
	{ path: demoPagesMenu.billSubVoucher.path, element: <BudgetHeader />, exact: true },
	{ path: demoPagesMenu.BudgetEmpProfile.path, element: <BudgetHeader />, exact: true },
    { path: budgetDashboard.BudgetEmployee.subMenu.EmployeeAttendanceInBudget.path, element: <BudgetHeader />, exact: true},	
	{ path: budgetDashboard.BudgetEmployee.subMenu.EmployeeListInBudget.path, element: <BudgetHeader />, exact: true},
	
	{ path: budgetDashboard.budgetHeads.subMenu.detailedHierarchy.path, element: <BudgetHeader />, exact: true},

	
	
	




	

];

export default headers;
